### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by ntzb** [bikerider331/plugin.video.filelist.ro.api#2]
first, thank you very much for the effort :)
when using search, the plugin gives an error:
```
2020-02-13 18:27:09.009 T:2827981696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: show_torrents() takes exactly 4 arguments (2 given)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.filelist.ro.api/main.py", line 334, in <module>
                                                indexer.router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.filelist.ro.api/main.py", line 315, in router
                                                self.startSearch()
                                              File "/storage/.kodi/addons/plugin.video.filelist.ro.api/main.py", line 286, in startSearch
                                                self.show_torrents(torrents)
                                            TypeError: show_torrents() takes exactly 4 arguments (2 given)
                                            -->End of Python script error report<--
2020-02-13 18:27:09.347 T:2879378304   ERROR: GetDirectory - Error getting plugin://plugin.video.filelist.ro.api/?action=search
2020-02-13 18:27:09.349 T:4066033680   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.filelist.ro.api/?action=search) failed
```

manually browsing and opening a torrent works ok.

**Comment by bikerider331** [comment]
Thank you very much for pointing this issue, today I fixed it and made a new release, please update the plugin and let me know if there are any issues. Also if you have any ideas on how to improve it please let me know and I'll see what I can do (python is new to me :D )
